cabal-version:      3.12
name:               pudu
version:            0.1.0.0
synopsis:           Pudu language compiler and tools
description:        A statically typed native systems language compiler with explicit safety and performance semantics.
category:           Language
maintainer:         chrismichaelps
license:            BSD-3-Clause
build-type:         Simple

source-repository head
  type:             git
  location:         https://github.com/chrismichaelps/pudu-lang.git

common warnings
  default-language: GHC2024
  default-extensions:
    NamedFieldPuns
    OverloadedStrings
    StrictData
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns

library
  import:           warnings
  hs-source-dirs:   src
  exposed-modules:
    Pudu.Diagnostic
    Pudu.Frontend.Lexer
    Pudu.Frontend.Lexer.Cursor
    Pudu.Frontend.Lexer.Identifier
    Pudu.Frontend.Lexer.Number
    Pudu.Frontend.Lexer.Quoted
    Pudu.Frontend.Lexer.Symbol
    Pudu.Frontend.Lexer.Trivia
    Pudu.Frontend.Parser.Name
    Pudu.Frontend.Parser.Declaration.Import
    Pudu.Frontend.Parser.Expression
    Pudu.Frontend.Parser.State
    Pudu.Frontend.Parser.Type
    Pudu.Frontend.Syntax
    Pudu.Frontend.Syntax.Located
    Pudu.Frontend.Syntax.Name
    Pudu.Frontend.Syntax.Tree
    Pudu.Frontend.Token
    Pudu.Source
  build-depends:
    base >=4.20 && <4.23,
    containers >=0.6 && <0.9,
    text >=2.1 && <2.2

test-suite pudu-test
  import:           warnings
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  other-modules:
    Pudu.DiagnosticSpec
    Pudu.Frontend.Lexer.CursorSpec
    Pudu.Frontend.LexerSpec
    Pudu.Frontend.Lexer.NumberSymbolSpec
    Pudu.Frontend.Lexer.QuotedSpec
    Pudu.Frontend.Lexer.ScannerSpec
    Pudu.Frontend.ParserStateNameSpec
    Pudu.Frontend.ParserImportSpec
    Pudu.Frontend.ParserExpressionSpec
    Pudu.Frontend.ParserTypeSpec
    Pudu.Frontend.SyntaxSpec
    Pudu.Frontend.TokenSpec
  build-depends:
    base >=4.20 && <4.23,
    pudu,
    QuickCheck >=2.15 && <2.17,
    text >=2.1 && <2.2
