#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
musl_runtime="${PUDU_LAMBDA_RUNTIME:-$root/dist/pudu-musl-lambda-x86_64}"
musl_loader="${PUDU_MUSL_LOADER:-$root/dist/ld-musl-x86_64.so.1}"
musl_library_dir="${PUDU_MUSL_LIBRARY_DIR:-$(dirname "$musl_loader")}"
musl_libraries=(libffi.so.8 libz.so.1 libncursesw.so.6 libgmp.so.10)
compiler="${PUDU:-pudu}"
output="$root/website/.vercel/output"
function_dir="$output/functions/dynamic.func"
search_index="$function_dir/website/data/search-index.pudu-data"

if [[ -z "${PUDU_SITE_URL:-}" ]]; then
  echo "set PUDU_SITE_URL to the canonical HTTPS origin" >&2
  exit 1
fi
site_url_json="${PUDU_SITE_URL//\\/\\\\}"
site_url_json="${site_url_json//\"/\\\"}"

# The dynamic half of the site is Pudu, not JavaScript.
#
# It was JavaScript for one reason: a runtime linked against a current glibc
# cannot start on the Lambda a Vercel function runs on, so the only language that
# could answer a request there was the platform's own. That meant a second copy
# of the ranking and of the page — a copy with no test against the Pudu one, so
# the two could disagree and the deployed one was the untested one.
#
# A runtime linked against musl starts there when its matching loader is carried
# beside it, so the function is the site itself: `website/src/Function.pudu`
# serving `Web.Dynamic`, rendering the shared search and missing views.
if [[ ! -f "$musl_runtime" ]]; then
  echo "no Lambda musl runtime at $musl_runtime" >&2
  echo "  build one with scripts/build-musl-runtime.sh, or set PUDU_LAMBDA_RUNTIME" >&2
  exit 1
fi
if [[ ! -f "$musl_loader" ]]; then
  echo "no packaged musl loader at $musl_loader" >&2
  echo "  build one with scripts/build-musl-runtime.sh, or set PUDU_MUSL_LOADER" >&2
  exit 1
fi
for dependency in "${musl_libraries[@]}"; do
  if [[ ! -f "$musl_library_dir/$dependency" ]]; then
    echo "no packaged musl library at $musl_library_dir/$dependency" >&2
    echo "  build the runtime package with scripts/build-musl-runtime.sh" >&2
    exit 1
  fi
done

rm -rf "$output"
mkdir -p "$function_dir/website/data" "$output/static/assets" "$output/static/fonts"
cp "$musl_loader" "$function_dir/ld-musl-x86_64.so.1"
for dependency in "${musl_libraries[@]}"; do
  cp "$musl_library_dir/$dependency" "$function_dir/$dependency"
done
cp "$root/website/public/site.css" "$output/static/assets/site.css"
cp "$root/website/public/assets/"* "$output/static/assets/"
cp "$root/website/public/fonts/"* "$output/static/fonts/"

# The complete documentation catalogue drives static generation. The function
# receives the smaller representation its search route consumes, generated by
# Pudu from that same validated source.
"$compiler" run "$root/website/src/SearchIndex.pudu" \
  "$root/website/data/api.json" "$search_index"
chmod 644 "$search_index" 2>/dev/null || true

# A custom runtime is started by running `bootstrap`, so the artefact is named
# that. The compiler attaching the program must be the same version of Pudu as
# the runtime it is attached to; both come from this checkout.
"$compiler" build "$root/website/src/Function.pudu" \
  -o "$function_dir/bootstrap" \
  --runtime "$musl_runtime"
chmod 755 "$function_dir/bootstrap" "$function_dir/ld-musl-x86_64.so.1"

# The static half of the site, rendered by the site.
#
# `Web.render` answers a response for a path, so producing every page is that
# many calls: no server is started, no port is taken, and the build makes no
# requests to itself. What is rendered is `Seo.paths`, the list the sitemap is
# built from, so the two cannot disagree about which pages exist.
PUDU_SITE_URL="$PUDU_SITE_URL" PUDU_CATALOG_PATH="$root/website/data/api.json" \
  "$compiler" run "$root/website/src/Prerender.pudu" "$output/static"

# `provided.al2023` runs the artefact directly: the platform starts `bootstrap` and
# speaks to it over the Lambda runtime interface, which `Std.Http.Server.Lambda`
# implements. No Node launcher, and nothing to add helpers to.
printf '%s\n' \
  '{' \
  '  "runtime": "provided.al2023",' \
  '  "handler": "bootstrap",' \
  '  "architecture": "x86_64",' \
  '  "environment": {' \
  "    \"PUDU_SITE_URL\": \"$site_url_json\"" \
  '  },' \
  '  "maxDuration": 60' \
  '}' > "$function_dir/.vc-config.json"

chmod 644 "$function_dir/.vc-config.json" 2>/dev/null || true

printf '%s\n' \
  '{' \
  '  "version": 3,' \
  '  "routes": [' \
  '    { "handle": "filesystem" },' \
  '    { "src": "/", "dest": "/index.html" },' \
  '    { "src": "/guide", "dest": "/guide/index.html" },' \
  '    { "src": "/about", "dest": "/about/index.html" },' \
  '    { "src": "/donate", "dest": "/donate/index.html" },' \
  '    { "src": "/modules", "dest": "/modules/index.html" },' \
  '    { "src": "/module/(.*)", "dest": "/module/$1/index.html" },' \
  '    { "src": "/docs/(.*)/(.*)/(.*)", "dest": "/docs/$1/$2/$3/index.html" },' \
  '    { "src": "/search", "dest": "/dynamic" },' \
  '    { "src": "/.*", "dest": "/dynamic" }' \
  '  ]' \
  '}' > "$output/config.json"

echo "Built $output"
