#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
musl_runtime="${PUDU_LAMBDA_RUNTIME:-$root/dist/pudu-musl-lambda-x86_64}"
musl_loader="${PUDU_MUSL_LOADER:-$root/dist/ld-musl-x86_64.so.1}"
musl_library_dir="${PUDU_MUSL_LIBRARY_DIR:-$(dirname "$musl_loader")}"
musl_libraries=(libffi.so.8 libz.so.1 libncursesw.so.6 libgmp.so.10)
compiler="${PUDU:-pudu}"
output="$root/website/.vercel/output"
function_dir="$output/functions/dynamic.func"
search_index="$function_dir/website/data/search-index.pudu-data"
examples_dir="$function_dir/website/playground/examples"

if [[ -z "${PUDU_SITE_URL:-}" ]]; then
  echo "set PUDU_SITE_URL to the canonical HTTPS origin" >&2
  exit 1
fi
site_url_json="${PUDU_SITE_URL//\\/\\\\}"
site_url_json="${site_url_json//\"/\\\"}"

# The playground's runner is named at build time because it is an address or
# a mode, not a secret. `local` runs programs inside the function, confined: the
# function carries the compiler, the standard library, and the sandbox, and the
# sandbox gives each program an emptied environment and the runtime's
# confinement. A runner's https:// address sends programs elsewhere instead;
# its shared secret is a project environment variable, PUDU_PLAYGROUND_TOKEN,
# which the platform gives the function when it runs, and is never written into
# the build output.
playground_runner="${PUDU_PLAYGROUND_RUNNER:-local}"
case "$playground_runner" in
  off|local|https://*) ;;
  *)
    echo "PUDU_PLAYGROUND_RUNNER must be off, local, or a runner's https:// address for a deployment" >&2
    exit 1
    ;;
esac
runner_json="${playground_runner//\\/\\\\}"
runner_json="${runner_json//\"/\\\"}"

# The dynamic half of the site is Pudu, not JavaScript.
#
# It was JavaScript for one reason: a runtime linked against a current glibc
# cannot start on the Lambda a Vercel function runs on, so the only language that
# could answer a request there was the platform's own. That meant a second copy
# of the ranking and of the page — a copy with no test against the Pudu one, so
# the two could disagree and the deployed one was the untested one.
#
# A runtime linked against musl starts there when its matching loader is carried
# beside it, so the function is the site itself: `website/src/Function.pudu`
# serving `Web.Dynamic`, rendering the shared search and missing views.
if [[ ! -f "$musl_runtime" ]]; then
  echo "no Lambda musl runtime at $musl_runtime" >&2
  echo "  build one with scripts/build-musl-runtime.sh, or set PUDU_LAMBDA_RUNTIME" >&2
  exit 1
fi
if [[ ! -f "$musl_loader" ]]; then
  echo "no packaged musl loader at $musl_loader" >&2
  echo "  build one with scripts/build-musl-runtime.sh, or set PUDU_MUSL_LOADER" >&2
  exit 1
fi
for dependency in "${musl_libraries[@]}"; do
  if [[ ! -f "$musl_library_dir/$dependency" ]]; then
    echo "no packaged musl library at $musl_library_dir/$dependency" >&2
    echo "  build the runtime package with scripts/build-musl-runtime.sh" >&2
    exit 1
  fi
done

rm -rf "$output"
mkdir -p "$function_dir/website/data" "$examples_dir" "$output/static/assets" "$output/static/fonts"
cp "$musl_loader" "$function_dir/ld-musl-x86_64.so.1"
for dependency in "${musl_libraries[@]}"; do
  cp "$musl_library_dir/$dependency" "$function_dir/$dependency"
done
cp "$root/website/public/site.css" "$output/static/assets/site.css"
# The playground's script is a folder of modules, one per layer, so the assets
# are copied with their folders.
cp -R "$root/website/public/assets/." "$output/static/assets/"
cp "$root/website/public/fonts/"* "$output/static/fonts/"

# The complete documentation catalogue drives static generation. The function
# receives the smaller representation its search route consumes, generated by
# Pudu from that same validated source.
"$compiler" run "$root/website/src/SearchIndex.pudu" \
  "$root/website/data/api.json" "$search_index"
chmod 644 "$search_index" 2>/dev/null || true

# The playground's examples are read by the function as they are by the site:
# once, before the first invocation. They are its menu, and a shared or posted
# program is recognised as one of them.
cp "$root/website/playground/examples/"*.pudu "$examples_dir/"
chmod 644 "$examples_dir/"*.pudu 2>/dev/null || true

# A custom runtime is started by running `bootstrap`, so the artefact is named
# that. The compiler attaching the program must be the same version of Pudu as
# the runtime it is attached to; both come from this checkout.
"$compiler" build "$root/website/src/Function.pudu" \
  -o "$function_dir/bootstrap" \
  --runtime "$musl_runtime"
chmod 755 "$function_dir/bootstrap" "$function_dir/ld-musl-x86_64.so.1"

# What the function runs a reader's program with: the same runtime, as the
# compiler, beside the library it reads and the sandbox that confines it.
if [[ "$playground_runner" == local ]]; then
  cp "$musl_runtime" "$function_dir/pudu"
  cp -R "$root/packages/pudu/v0.1/lib" "$function_dir/lib"
  cp "$root/website/playground/sandbox.sh" "$function_dir/website/playground/sandbox.sh"
  chmod 755 "$function_dir/pudu" "$function_dir/website/playground/sandbox.sh"
  chmod -R a+rX "$function_dir/lib"
fi

# The static half of the site, rendered by the site.
#
# `Web.render` answers a response for a path, so producing every page is that
# many calls: no server is started, no port is taken, and the build makes no
# requests to itself. What is rendered is `Seo.paths`, the list the sitemap is
# built from, so the two cannot disagree about which pages exist.
PUDU_SITE_URL="$PUDU_SITE_URL" PUDU_CATALOG_PATH="$root/website/data/api.json" \
  PUDU_DOCS_PATH="$root/website/docs" \
  PUDU_RELEASES_PATH="$root/website/data/releases.json" \
  PUDU_DOCUMENTS_PATH="$root" \
  PUDU_RELEASE_NOTES_PATH="$root/packages/pudu/v0.1/release-notes" \
  PUDU_PLAYGROUND_EXAMPLES="$root/website/playground/examples" \
  PUDU_PLAYGROUND_RUNNER="$playground_runner" \
  PUDU_PLAYGROUND_ISOLATION=confined \
  PUDU_PLAYGROUND_TOKEN="${PUDU_PLAYGROUND_TOKEN:-prerender}" \
  "$compiler" run "$root/website/src/Prerender.pudu" "$output/static"

# `provided.al2023` runs the artefact directly: the platform starts `bootstrap` and
# speaks to it over the Lambda runtime interface, which `Std.Http.Server.Lambda`
# implements. No Node launcher, and nothing to add helpers to.
printf '%s\n' \
  '{' \
  '  "runtime": "provided.al2023",' \
  '  "handler": "bootstrap",' \
  '  "architecture": "x86_64",' \
  '  "environment": {' \
  "    \"PUDU_SITE_URL\": \"$site_url_json\"," \
  "    \"PUDU_PLAYGROUND_RUNNER\": \"$runner_json\"," \
  '    "PUDU_PLAYGROUND_ISOLATION": "confined",' \
  '    "PUDU_PLAYGROUND_COMPILER": "/var/task/pudu",' \
  '    "PUDU_PLAYGROUND_LIBRARY": "/var/task/lib",' \
  '    "PUDU_PLAYGROUND_SANDBOX": "/var/task/website/playground/sandbox.sh",' \
  '    "PUDU_PLAYGROUND_WORKSPACE": "/tmp"' \
  '  },' \
  '  "maxDuration": 60' \
  '}' > "$function_dir/.vc-config.json"

chmod 644 "$function_dir/.vc-config.json" 2>/dev/null || true

# The guide became the documentation. Its old address is answered with a
# permanent redirect rather than a second rendering, so a link to it keeps
# working, a crawler is told which address to keep, and the sitemap carries one
# address for one page.
#
# A page reaches the CDN only when a route sends it there. The list used to be
# written by hand, so every page added after it was written fell through to the
# catch-all and was answered by the function, which serves only search and the
# no-index fallback. It is read from what was actually rendered instead: every
# top-level directory holding an index.html gets the route that serves it.
page_routes=""
while IFS= read -r page; do
  name="$(basename "$(dirname "$page")")"
  page_routes="$page_routes    { \"src\": \"/$name\", \"dest\": \"/$name/index.html\" },
"
done < <(find "$output/static" -mindepth 2 -maxdepth 2 -name index.html | sort)

# Each playground example is a rendered page one level below the playground.
# Listed by name, like the pages above, so an address that is not an example —
# the shared-program page among them — reaches the function.
example_routes=""
while IFS= read -r page; do
  name="$(basename "$(dirname "$page")")"
  example_routes="$example_routes    { \"src\": \"/playground/$name\", \"dest\": \"/playground/$name/index.html\" },
"
done < <(find "$output/static/playground" -mindepth 2 -maxdepth 2 -name index.html 2>/dev/null | sort)

{
  # Running a program is a post, and a post is never a static file: it is sent
  # to the function before the platform looks for one. Both APIs — running a
  # program and asking about one — and a shared program are the function's too.
  # The script modules import one another without a version in their address,
  # so each is checked again on every load.
  printf '%s\n' '{' '  "version": 3,' '  "routes": [' \
    '    { "src": "/playground", "methods": ["POST"], "dest": "/dynamic" },' \
    '    { "src": "/api/playground/(run|assist)", "dest": "/dynamic" },' \
    '    { "src": "/assets/playground/(.*)", "headers": { "cache-control": "public, max-age=0, must-revalidate" }, "continue": true },' \
    '    { "src": "/assets/docs/(.*)", "headers": { "cache-control": "public, max-age=0, must-revalidate" }, "continue": true },' \
    '    { "src": "/playground/shared", "dest": "/dynamic" },' \
    '    { "handle": "filesystem" },'
  printf '%s' "$page_routes"
  printf '%s' "$example_routes"
  printf '%s\n' \
    '    { "src": "/", "dest": "/index.html" },' \
    '    { "src": "/module/(.*)", "dest": "/module/$1/index.html" },' \
    '    { "src": "/docs/(.*)/(.*)/(.*)", "dest": "/docs/$1/$2/$3/index.html" },' \
    '    { "src": "/docs/([^/]+)", "dest": "/docs/$1/index.html" },' \
    '    { "src": "/guide", "status": 308, "headers": { "Location": "/docs" } },' \
    '    { "src": "/search", "dest": "/dynamic" },' \
    '    { "src": "/.*", "dest": "/dynamic" }' \
    '  ]' \
    '}'
} > "$output/config.json"

echo "Built $output"
