name: ci

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

permissions:
  contents: read

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.14.1
          cabal-version: 3.16.1.0
      - run: cabal update
      - run: cabal build all --enable-optimization=2
      - run: cabal test all --enable-optimization=2 --test-show-details=direct
